# Generated by Django 5.2.3 on 2026-06-18 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('professionals', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalEvolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('time', models.TimeField(verbose_name='hora')),
                ('service_description', models.TextField(verbose_name='descricao do atendimento')),
                ('procedures_performed', models.TextField(blank=True, verbose_name='procedimentos realizados')),
                ('conduct', models.TextField(blank=True, verbose_name='conduta')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_evolutions', to='scheduling.appointment', verbose_name='agendamento')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_evolutions', to='patients.patient', verbose_name='paciente')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_evolutions', to='professionals.professional', verbose_name='profissional')),
            ],
            options={
                'verbose_name': 'evolucao clinica',
                'verbose_name_plural': 'evolucoes clinicas',
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['patient', 'date', 'time'], name='medical_rec_patient_7f594d_idx'), models.Index(fields=['professional', 'date'], name='medical_rec_profess_7f377a_idx')],
            },
        ),
    ]
