# Generated by Django 5.2.3 on 2026-06-18 01:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_patient_status'),
        ('professionals', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='data inicial')),
                ('end_date', models.DateField(verbose_name='data final')),
                ('appointment_quantity', models.PositiveIntegerField(default=0, verbose_name='quantidade de atendimentos realizados')),
                ('total_billed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='valor total faturado')),
                ('company_receivable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='valor a receber pela empresa')),
                ('professional_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='valor a receber pelo profissional')),
                ('pending_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='valores pendentes')),
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='gerado em')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_closings', to='professionals.professional', verbose_name='profissional')),
            ],
            options={
                'verbose_name': 'fechamento mensal',
                'verbose_name_plural': 'fechamentos mensais',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField(verbose_name='data de referencia')),
                ('appointment_quantity', models.PositiveIntegerField(default=1, verbose_name='quantidade de atendimentos')),
                ('appointment_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor do atendimento')),
                ('payer_type', models.CharField(choices=[('private', 'Particular'), ('insurance', 'Convenio')], max_length=20, verbose_name='tipo de recebimento')),
                ('insurance_name', models.CharField(blank=True, max_length=120, verbose_name='convenio')),
                ('professional_specialty', models.CharField(blank=True, max_length=120, verbose_name='especialidade')),
                ('company_percentage', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, verbose_name='percentual da empresa')),
                ('professional_percentage', models.DecimalField(decimal_places=2, default=Decimal('70.00'), max_digits=5, verbose_name='percentual do profissional')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='valor total faturado')),
                ('company_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='valor da empresa')),
                ('professional_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='valor do profissional')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('received', 'Recebido'), ('paid', 'Pago ao profissional'), ('canceled', 'Cancelado')], default='pending', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_entry', to='scheduling.appointment', verbose_name='agendamento')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_entries', to='patients.patient', verbose_name='paciente')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_entries', to='professionals.professional', verbose_name='profissional')),
            ],
            options={
                'verbose_name': 'lancamento financeiro',
                'verbose_name_plural': 'lancamentos financeiros',
                'ordering': ['-reference_date', 'professional', 'patient'],
                'indexes': [models.Index(fields=['reference_date'], name='finance_fin_referen_435221_idx'), models.Index(fields=['professional', 'reference_date'], name='finance_fin_profess_af889b_idx'), models.Index(fields=['patient', 'reference_date'], name='finance_fin_patient_fea85a_idx'), models.Index(fields=['payer_type'], name='finance_fin_payer_t_9d6c58_idx'), models.Index(fields=['status'], name='finance_fin_status_064393_idx')],
            },
        ),
    ]
