# Generated by Django 5.2.3 on 2026-06-18 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=30, verbose_name='RG')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('sex', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro'), ('N', 'Nao informado')], default='N', max_length=1, verbose_name='sexo')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('zip_code', models.CharField(blank=True, max_length=12, verbose_name='CEP')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='logradouro')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='numero')),
                ('complement', models.CharField(blank=True, max_length=120, verbose_name='complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=120, verbose_name='bairro')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('professional_council', models.CharField(blank=True, max_length=30, verbose_name='conselho profissional')),
                ('council_number', models.CharField(blank=True, max_length=50, verbose_name='numero do conselho')),
                ('council_state', models.CharField(blank=True, max_length=2, verbose_name='UF do conselho')),
                ('primary_specialty', models.CharField(blank=True, max_length=120, verbose_name='especialidade principal')),
                ('secondary_specialties', models.TextField(blank=True, verbose_name='especialidades secundarias')),
                ('hired_at', models.DateField(blank=True, null=True, verbose_name='data de contratacao')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'profissional',
                'verbose_name_plural': 'profissionais',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='titulo')),
                ('document_type', models.CharField(choices=[('diploma', 'Diploma'), ('certificate', 'Certificado'), ('council_registration', 'Registro do conselho'), ('personal_document', 'Documento pessoal'), ('proof', 'Comprovante'), ('other', 'Outro arquivo')], default='other', max_length=40, verbose_name='tipo')),
                ('file', models.FileField(upload_to='professionals/documents/%Y/%m/', verbose_name='arquivo')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='professionals.professional', verbose_name='profissional')),
            ],
            options={
                'verbose_name': 'documento do profissional',
                'verbose_name_plural': 'documentos dos profissionais',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
