# Generated by Django 5.2.3 on 2026-06-18 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('specialty', models.CharField(choices=[('orthopedic', 'Avaliacao Ortopedica'), ('gerontological', 'Avaliacao Gerontologica'), ('cardiorespiratory', 'Avaliacao Cardiorrespiratoria'), ('neurological', 'Avaliacao Neurologica'), ('custom', 'Avaliacao Personalizada')], max_length=40, verbose_name='especialidade')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'modelo de avaliacao',
                'verbose_name_plural': 'modelos de avaliacao',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=180, verbose_name='rotulo')),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Numero'), ('scale', 'Escala'), ('boolean', 'Sim/Nao'), ('date', 'Data')], max_length=20, verbose_name='tipo de campo')),
                ('unit', models.CharField(blank=True, max_length=40, verbose_name='unidade')),
                ('is_required', models.BooleanField(default=False, verbose_name='obrigatorio')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='assessments.assessmenttemplate', verbose_name='modelo')),
            ],
            options={
                'verbose_name': 'campo de avaliacao',
                'verbose_name_plural': 'campos de avaliacao',
                'ordering': ['template', 'order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(verbose_name='data e hora da avaliacao')),
                ('summary', models.TextField(blank=True, verbose_name='resumo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_assessments', to='patients.patient', verbose_name='paciente')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_assessments', to='professionals.professional', verbose_name='profissional')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='assessments.assessmenttemplate', verbose_name='modelo')),
            ],
            options={
                'verbose_name': 'avaliacao clinica',
                'verbose_name_plural': 'avaliacoes clinicas',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='indicador')),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor numerico')),
                ('text_value', models.TextField(blank=True, verbose_name='valor textual')),
                ('unit', models.CharField(blank=True, max_length=40, verbose_name='unidade')),
                ('higher_is_better', models.BooleanField(default=True, verbose_name='maior e melhor')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='assessments.assessmentfield', verbose_name='campo')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='assessments.clinicalassessment', verbose_name='avaliacao')),
            ],
            options={
                'verbose_name': 'metrica de avaliacao',
                'verbose_name_plural': 'metricas de avaliacao',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='clinicalassessment',
            index=models.Index(fields=['patient', 'performed_at'], name='assessments_patient_66a716_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalassessment',
            index=models.Index(fields=['template', 'performed_at'], name='assessments_templat_1446c1_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentmetric',
            index=models.Index(fields=['name'], name='assessments_name_b87424_idx'),
        ),
    ]
