# Generated by Django 5.2.3 on 2026-06-18 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('starts_at', models.TimeField(verbose_name='hora inicial')),
                ('ends_at', models.TimeField(verbose_name='hora final')),
                ('appointment_type', models.CharField(choices=[('nursing', 'Enfermagem'), ('physiotherapy', 'Fisioterapia'), ('medical', 'Atendimento medico'), ('caregiver', 'Cuidador'), ('speech_therapy', 'Fonoaudiologia'), ('occupational_therapy', 'Terapia ocupacional'), ('other', 'Outro')], default='other', max_length=40, verbose_name='tipo de atendimento')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('confirmed', 'Confirmado'), ('in_progress', 'Em atendimento'), ('completed', 'Finalizado'), ('canceled', 'Cancelado')], default='scheduled', max_length=20, verbose_name='status')),
                ('recurrence_frequency', models.CharField(choices=[('none', 'Nao repetir'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensal')], default='none', max_length=20, verbose_name='recorrencia')),
                ('recurrence_interval', models.PositiveSmallIntegerField(default=1, verbose_name='intervalo da recorrencia')),
                ('recurrence_weekdays', models.CharField(blank=True, help_text='Use numeros separados por virgula: 0=segunda, 1=terca, ..., 6=domingo.', max_length=30, verbose_name='dias da semana')),
                ('recurrence_until', models.DateField(blank=True, null=True, verbose_name='repetir ate')),
                ('recurrence_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='quantidade de repeticoes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient', verbose_name='paciente')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='professionals.professional', verbose_name='profissional')),
            ],
            options={
                'verbose_name': 'agendamento',
                'verbose_name_plural': 'agendamentos',
                'ordering': ['date', 'starts_at'],
                'indexes': [models.Index(fields=['date', 'starts_at'], name='scheduling__date_07f6b7_idx'), models.Index(fields=['professional', 'date'], name='scheduling__profess_225d3f_idx'), models.Index(fields=['patient', 'date'], name='scheduling__patient_eebfa1_idx'), models.Index(fields=['status'], name='scheduling__status_1008cc_idx')],
            },
        ),
    ]
