# Generated by Django 5.2.3 on 2026-06-18 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('sex', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro'), ('N', 'Nao informado')], default='N', max_length=1, verbose_name='sexo')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('zip_code', models.CharField(blank=True, max_length=12, verbose_name='CEP')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='logradouro')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='numero')),
                ('complement', models.CharField(blank=True, max_length=120, verbose_name='complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=120, verbose_name='bairro')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('primary_diagnosis', models.CharField(blank=True, max_length=255, verbose_name='diagnostico principal')),
                ('secondary_diagnoses', models.TextField(blank=True, verbose_name='diagnosticos secundarios')),
                ('comorbidities', models.TextField(blank=True, verbose_name='comorbidades')),
                ('allergies', models.TextField(blank=True, verbose_name='alergias')),
                ('current_medications', models.TextField(blank=True, verbose_name='medicamentos em uso')),
                ('clinical_notes', models.TextField(blank=True, verbose_name='observacoes clinicas')),
                ('responsible_name', models.CharField(blank=True, max_length=255, verbose_name='nome do responsavel')),
                ('responsible_relationship', models.CharField(blank=True, max_length=80, verbose_name='grau de parentesco')),
                ('responsible_phone', models.CharField(blank=True, max_length=30, verbose_name='telefone do responsavel')),
                ('responsible_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail do responsavel')),
                ('referring_professional_name', models.CharField(blank=True, max_length=255, verbose_name='medico/fisioterapeuta responsavel')),
                ('referring_professional_specialty', models.CharField(blank=True, max_length=120, verbose_name='especialidade')),
                ('referring_professional_council', models.CharField(blank=True, max_length=50, verbose_name='CRM/conselho')),
                ('referring_professional_phone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('referring_professional_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('assigned_professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='professionals.professional', verbose_name='profissional interno responsavel')),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'ordering': ['full_name'],
            },
        ),
    ]
