# Generated by Django 5.2.3 on 2026-06-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_at', models.DateTimeField(blank=True, null=True, verbose_name='horario do check-in')),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude do check-in')),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude do check-in')),
                ('check_in_distance_meters', models.PositiveIntegerField(blank=True, null=True, verbose_name='distancia no check-in')),
                ('check_in_radius_meters', models.PositiveSmallIntegerField(choices=[(50, '50 metros'), (100, '100 metros'), (200, '200 metros')], default=100, verbose_name='raio permitido')),
                ('check_in_allowed', models.BooleanField(default=False, verbose_name='check-in permitido')),
                ('check_out_at', models.DateTimeField(blank=True, null=True, verbose_name='horario do check-out')),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude do check-out')),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude do check-out')),
                ('check_out_distance_meters', models.PositiveIntegerField(blank=True, null=True, verbose_name='distancia no check-out')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='duracao em minutos')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'registro de check-in/check-out',
                'verbose_name_plural': 'registros de check-in/check-out',
                'ordering': ['-check_in_at', '-created_at'],
            },
        ),
    ]
