# Generated by Django 5.2.3 on 2026-06-18 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_record', to='scheduling.appointment', verbose_name='agendamento'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['check_in_at'], name='attendance__check_i_73cb8c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['check_in_allowed'], name='attendance__check_i_8248fd_idx'),
        ),
    ]
