# Generated by Django 5.2.3 on 2026-06-18 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='titulo')),
                ('document_type', models.CharField(choices=[('lab_exam', 'Exame laboratorial'), ('image_exam', 'Exame de imagem'), ('prescription', 'Receita medica'), ('report', 'Relatorio'), ('medical_report', 'Laudo'), ('pdf', 'PDF'), ('photo', 'Foto'), ('other', 'Outro')], max_length=30, verbose_name='tipo de documento')),
                ('file', models.FileField(upload_to='patients/documents/%Y/%m/', verbose_name='arquivo')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='data do documento')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient', verbose_name='paciente')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_patient_documents', to='professionals.professional', verbose_name='profissional responsavel')),
            ],
            options={
                'verbose_name': 'exame/documento do paciente',
                'verbose_name_plural': 'exames e documentos dos pacientes',
                'ordering': ['-document_date', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'document_type'], name='patient_doc_patient_d1cbb3_idx'), models.Index(fields=['document_date'], name='patient_doc_documen_5bc4c5_idx')],
            },
        ),
    ]
