# Generated by Django 5.2.3 on 2026-06-18 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('professionals', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('time', models.TimeField(verbose_name='hora')),
                ('description', models.TextField(verbose_name='descricao da intercorrencia')),
                ('severity', models.CharField(choices=[('mild', 'Leve'), ('moderate', 'Moderada'), ('severe', 'Grave'), ('critical', 'Critica')], max_length=20, verbose_name='gravidade')),
                ('conduct_performed', models.TextField(blank=True, verbose_name='conduta realizada')),
                ('classification', models.CharField(choices=[('mild', 'Leve'), ('moderate', 'Moderada'), ('severe', 'Grave'), ('critical', 'Critica')], max_length=20, verbose_name='classificacao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='scheduling.appointment', verbose_name='agendamento')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='patients.patient', verbose_name='paciente')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='professionals.professional', verbose_name='profissional')),
            ],
            options={
                'verbose_name': 'intercorrencia',
                'verbose_name_plural': 'intercorrencias',
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['patient', 'date'], name='incidents_i_patient_80e85f_idx'), models.Index(fields=['professional', 'date'], name='incidents_i_profess_d9ff45_idx'), models.Index(fields=['classification'], name='incidents_i_classif_a3c2c8_idx')],
            },
        ),
    ]
